### ISSUE TITLE
anudeepND whitelist & Pi-hole Commonly Whitelisted Domains

### ISSUE THREAD

**Issue by HellboyPI** [notracking/hosts-blocklists-scripts#1]
Github user [anudeepND](https://github.com/anudeepND) is maintaining a [whitelist](https://github.com/anudeepND/whitelist). 
There is also a [Commonly Whitelisted Domains](https://discourse.pi-hole.net/t/commonly-whitelisted-domains/212) thread over at Pi-hole forum. 
Maybe this gives you new ideas for your whitelist.

**Comment by notracking** [comment]
I've been keeping an eye out for these and I've got some more.
Using this ticket to make an overview.

[Windows Update Servers](https://github.com/crazy-max/WindowsSpyBlocker/blob/master/data/hosts/update.txt)
[Whitelist used in script](https://github.com/nlopez/adblock_hosts/blob/master/adblock_hosts/adblock_hosts.py)
[dshield Approved whitelist](http://www.dshield.org/feeds/suspiciousdomains_whitelist_approved.txt)
[wally3k (bottom of page)](https://wally3k.github.io/)
[blahdns Whitelist](https://github.com/ookangzheng/blahdns/blob/master/hosts/whitelist.txt)
[raghavdua1995](https://raw.githubusercontent.com/raghavdua1995/DNSlock-PiHole-whitelist/master/whitelist.list)

**Comment by notracking** [comment]
I've checked all these lists the last couple of days and all useful entries have been merged in to our whitelist.
Will keep an eye out for updates on these lists in the future.
