### ISSUE TITLE
Still not published?

### ISSUE THREAD

**Issue by Cubox** [notracking/hosts-blocklists-scripts#2]
It would be really nice if you could publish the tool, I am assuming some people would like to customise the source set.

**Comment by compliment** [comment]
Ping.

**Comment by notracking** [comment]
This ticket has been open for so long now. As explained before, it is not a single tool. At this stage I've set up several databases, scripts, services and cronjobs in all sorts of languages as all of these tools have been developed over a long period of time.

I do not want to support/explain this undocumented pile of software, nor do I want others to break their systems using them incorrectly. Only if in the future I decided to do a full rewrite, it will be done publicly.
