### ISSUE TITLE
fonts.gstatic.com is  listed in hostnames.whitelist.txt

### ISSUE THREAD

**Issue by cbuijs** [notracking/hosts-blocklists-scripts#3]
Hi,

The domain `fonts.gstatic.com`(line [86](https://github.com/notracking/hosts-blocklists-scripts/blob/master/hostnames.whitelist.txt#L86) as of this writing) is (still) whitelisted in [hostnames.whitelist.txt](https://github.com/notracking/hosts-blocklists-scripts/blob/master/hostnames.whitelist.txt).

See [Notracking issue 128](https://github.com/notracking/hosts-blocklists/issues/128).

**Comment by notracking** [comment]
fixed!
